### ISSUE TITLE
Dark theme list out of bounds

### ISSUE THREAD

**Issue by hex007** [rxbrad/es-theme-gbz35#6]
The following pic tells all too well. The list should scroll when last item is out of bounds

![img_20170416_155419](https://cloud.githubusercontent.com/assets/1689246/25074976/fa78456a-22bd-11e7-8925-fc3c4b0d1733.jpg)

**Comment by rxbrad** [comment]
Hmm.. Technically that should affect all systems that haven't been scraped. What resolution are you running at so I can test it? 

Emulationstation can be finicky with staying inbounds sometimes at certain resolutions, because everything is arranged by % distance. Shorten the list, and you get obvious blank space at the bottom. Lengthen it, and items fall out of bounds.

**Comment by hex007** [comment]
Framebuffer 320*240
Overscan 0,-16,-16,-16
Screen 3.5 inch 4:3 aspect ratio

I think having blank space is better than an overflowing list.

**Comment by rxbrad** [comment]
I believe I have this fixed in 1.12.  Tested Basic & Detailed layouts at 1024x768,1920x1080,640x480,320x240, 1280x720, and 1024x576.
