### ISSUE TITLE
would you like to add this theme to RetroPie-Setup?

### ISSUE THREAD

**Issue by meleu** [rxbrad/es-theme-gbz35#8]
Hi @rxbrad !

Sorry if I'm misusing your issue tracker. :)

Our fellow @hex007 requested to add your theme to RetroPie-Setup and the dark one as well (the dark branch on this same repository).

I can add the default to RetroPie-Setup (actually submit a PR to RetroPie-Setup repository), but the themes added to RetroPie-Setup must be the master branch on their own repository. If you want to see the dark theme installable too, you'll need to create a dedicated repo.

Nice job, by the way.

Cheers!

**Comment by rxbrad** [comment]
That would be great!  Before we do that, I have a few quick changes I'd like to make (most notably, adding video support, which I'm almost ready to push to my git).  Give me a day or two.

**Comment by meleu** [comment]
I think that users with a system powered by battery don't use video preview. But OK, I'll wait your sign.

Cheers!

**Comment by rxbrad** [comment]
You underestimate what people will do on their homemade gadgets, simply because they can. :)

Anyhow, I think it's ready to be added to RetroPie-Setup -- both the light & dark theme!

https://github.com/rxbrad/es-theme-gbz35
https://github.com/rxbrad/es-theme-gbz35-dark

Thanks again for setting this up for me!

**Comment by meleu** [comment]
Will do it as soon as I get home. Thanks!

Closing the issue here.
